version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: merenda
      POSTGRES_USER: ${POSTGRES_USER:-CayqueSilva}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Kiq3506!}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - SimpliSoft
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: cayquesilva/merendaflow-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER:-CayqueSilva}:${POSTGRES_PASSWORD:-Kiq3506!}@db:5432/merenda"
      FRONTEND_URL: ${FRONTEND_URL:-https://merenda.simplisoft.com.br}
      CHROME_BIN: /usr/bin/chromium-browser
    depends_on:
      - db
    networks:
      - SimpliSoft
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        # Habilita o Traefik para este serviço
        - "traefik.enable=true"
        # Define o roteador para o serviço backend
        - "traefik.http.routers.merendaflow-backend.rule=Host(`api.merenda.simplisoft.com.br`)" # Substitua pelos seus domínios
        - "traefik.http.routers.merendaflow-backend.entrypoints=web,websecure" # Usa o entrypoint HTTPS (se configurado no Traefik)
        - "traefik.http.routers.merendaflow-backend.tls.certresolver=letsencryptresolver" # <-- Mantenha este nome
        # Define o serviço (onde o tráfego será enviado)
        - "traefik.http.services.merendaflow-backend.loadbalancer.server.port=3001" # Porta que seu backend EXPÕE internamente
        # Opcional: Middleware de redirecionamento HTTP para HTTPS
        # - "traefik.http.middlewares.merendaflow-redirect-https.redirectscheme.scheme=https"

  frontend:
    image: cayquesilva/merendaflow-frontend:latest
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://api.merenda.simplisoft.com.br}
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - SimpliSoft
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        # Habilita o Traefik para este serviço
        - "traefik.enable=true"
        # Define o roteador para o serviço frontend (seu domínio principal)
        - "traefik.http.routers.merendaflow-frontend.rule=Host(`merenda.simplisoft.com.br`)" # Substitua pelos seus domínios
        - "traefik.http.routers.merendaflow-frontend.entrypoints=web,websecure"
        - "traefik.http.routers.merendaflow-frontend.tls.certresolver=letsencryptresolver" # <-- Mantenha este nome
        # Define o serviço (onde o tráfego será enviado)
        - "traefik.http.services.merendaflow-frontend.loadbalancer.server.port=3000" # Porta que seu frontend (Nginx) EXPÕE internamente
        # Reutiliza o middleware de redirecionamento se definido globalmente ou no backend

volumes:
  postgres_data:
    driver: local

networks:
  SimpliSoft:
    external: true # Assume que esta rede é criada e gerenciada pelo Traefik
