version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: merenda
      POSTGRES_USER: ${POSTGRES_USER:-CayqueSilva}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Kiq3506!}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - merendaflow-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-CayqueSilva}:${POSTGRES_PASSWORD:-Kiq3506!}@db:5432/merenda
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - merendaflow-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - merendaflow-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    driver: local

networks:
  merendaflow-network:
    driver: overlay
    attachable: true