version: "3.8"

services:
  db:
    image: postgres:15 # Usando uma imagem oficial e atual do PostgreSQL
    container_name: merendaflow_db
    restart: always
    environment:
      POSTGRES_DB: merenda
      POSTGRES_USER: CayqueSilva
      POSTGRES_PASSWORD: Kiq3506! # Use uma senha mais forte em um projeto real
    ports:
      - "5432:5432" # Expõe a porta do banco de dados para sua máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garante que os dados persistam

volumes:
  postgres_data:
