version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: merenda
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - merendaflow-network
    secrets:
      - postgres_user
      - postgres_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    image: merendaflow-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:5432/merenda
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - merendaflow-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  frontend:
    image: merendaflow-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - merendaflow-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data:
    driver: local

networks:
  merendaflow-network:
    driver: overlay
    attachable: true

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true